name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Building linters image ...
            run: make linters

          - name: Running linters ...
            run: make tox

          - name: Check build
            run: docker build . -f pkg/docker/Dockerfile.alpine
